#!/usr/bin/env python3
from pathlib import Path

p=Path('public/controller/app.js')
s=p.read_text()
old="""function mediaSessionTargetOptions(){return configuredDisplayTargets(false).map(([id,name])=>`<option value=\"${esc(id)}\">${esc(name)}</option>`).join('')}
function ensureMediaSessionControls(){
  const page=document.getElementById('media');if(!page||document.getElementById('mediaSessionControls'))return;
  const panel=document.createElement('div');panel.id='mediaSessionControls';panel.className='panel';panel.innerHTML=`<h3 style=\"margin-top:0\">Live Video Playback</h3><div class=\"muted\">Control the video element already playing on a receiver. Volume, pause, seek, and playback-rate changes do not reload the MP4.</div><div class=\"grid2\" style=\"margin-top:10px\"><label>Display<select id=\"mediaSessionTarget\">${mediaSessionTargetOptions()}</select></label><label>Playback Rate<select id=\"mediaSessionRate\"><option>.5</option><option>.75</option><option selected>1</option><option>1.25</option><option>1.5</option><option>2</option></select></label></div><div class=\"toolbar\" style=\"margin-top:10px\"><button onclick=\"mediaSessionCommand('play')\">Play</button><button onclick=\"mediaSessionCommand('pause')\">Pause</button><button onclick=\"mediaSessionCommand('restart')\">Restart Clip</button><button onclick=\"mediaSessionCommand('stop')\">Stop / Rewind</button><button onclick=\"mediaSessionSeekRelative(-10)\">−10s</button><button onclick=\"mediaSessionSeekRelative(10)\">+10s</button></div><label style=\"display:block;margin-top:10px\">Position <span id=\"mediaSessionPositionLabel\">0:00 / --:--</span><input id=\"mediaSessionSeek\" type=\"range\" min=\"0\" max=\"1\" step=\"0.1\" value=\"0\" style=\"width:100%\" onchange=\"mediaSessionCommand('seek',{positionSeconds:Number(this.value)})\"></label><label style=\"display:block;margin-top:10px\">Volume <span id=\"mediaSessionVolumeLabel\">100%</span><input id=\"mediaSessionVolume\" type=\"range\" min=\"0\" max=\"100\" step=\"1\" value=\"100\" style=\"width:100%\" oninput=\"mediaSessionVolumeLabel.textContent=this.value+'%'\" onchange=\"mediaSessionCommand('volume',{volume:Number(this.value)/100})\"></label><div id=\"mediaSessionStatus\" class=\"muted\" style=\"margin-top:8px\">No playback telemetry yet.</div>`;page.appendChild(panel);mediaSessionTarget.onchange=refreshMediaSessionControls;mediaSessionRate.onchange=()=>mediaSessionCommand('rate',{playbackRate:Number(mediaSessionRate.value)});clearInterval(mediaSessionRefreshTimer);mediaSessionRefreshTimer=setInterval(()=>{if(document.getElementById('media')?.classList.contains('active'))refreshMediaSessionControls()},1000)
}
"""
new="""function syncMediaSessionTargets(){
  const select=document.getElementById('mediaSessionTarget');if(!select)return;
  const targets=configuredDisplayTargets(false),signature=JSON.stringify(targets.map(([id,name])=>[String(id),String(name)]));
  if(select.dataset.targetSignature===signature)return;
  const old=select.value;select.replaceChildren(...targets.map(([id,name])=>new Option(String(name),String(id))));select.dataset.targetSignature=signature;
  if([...select.options].some(o=>o.value===old))select.value=old;
}
function ensureMediaSessionControls(){
  const page=document.getElementById('media');if(!page||document.getElementById('mediaSessionControls'))return;
  const panel=document.createElement('div');panel.id='mediaSessionControls';panel.className='panel';panel.innerHTML=`<h3 style=\"margin-top:0\">Live Video Playback</h3><div class=\"muted\">Control the video element already playing on a receiver. Volume, pause, seek, and playback-rate changes do not reload the MP4.</div><div class=\"grid2\" style=\"margin-top:10px\"><label>Display<select id=\"mediaSessionTarget\"></select></label><label>Playback Rate<select id=\"mediaSessionRate\"><option>.5</option><option>.75</option><option selected>1</option><option>1.25</option><option>1.5</option><option>2</option></select></label></div><div class=\"toolbar\" style=\"margin-top:10px\"><button onclick=\"mediaSessionCommand('play')\">Play</button><button onclick=\"mediaSessionCommand('pause')\">Pause</button><button onclick=\"mediaSessionCommand('restart')\">Restart Clip</button><button onclick=\"mediaSessionCommand('stop')\">Stop / Rewind</button><button onclick=\"mediaSessionSeekRelative(-10)\">−10s</button><button onclick=\"mediaSessionSeekRelative(10)\">+10s</button></div><label style=\"display:block;margin-top:10px\">Position <span id=\"mediaSessionPositionLabel\">0:00 / --:--</span><input id=\"mediaSessionSeek\" type=\"range\" min=\"0\" max=\"1\" step=\"0.1\" value=\"0\" style=\"width:100%\" onchange=\"mediaSessionCommand('seek',{positionSeconds:Number(this.value)})\"></label><label style=\"display:block;margin-top:10px\">Volume <span id=\"mediaSessionVolumeLabel\">100%</span><input id=\"mediaSessionVolume\" type=\"range\" min=\"0\" max=\"100\" step=\"1\" value=\"100\" style=\"width:100%\" oninput=\"mediaSessionVolumeLabel.textContent=this.value+'%'\" onchange=\"mediaSessionCommand('volume',{volume:Number(this.value)/100})\"></label><div id=\"mediaSessionStatus\" class=\"muted\" style=\"margin-top:8px\">No playback telemetry yet.</div>`;page.appendChild(panel);syncMediaSessionTargets();mediaSessionTarget.onchange=refreshMediaSessionControls;mediaSessionRate.onchange=()=>mediaSessionCommand('rate',{playbackRate:Number(mediaSessionRate.value)});clearInterval(mediaSessionRefreshTimer);mediaSessionRefreshTimer=setInterval(()=>{if(document.getElementById('media')?.classList.contains('active'))refreshMediaSessionControls()},1000)
}
"""
if old not in s: raise SystemExit('media session controls source block not found')
s=s.replace(old,new,1)
old_refresh="if(!window.mediaSessionTarget)return;const options=mediaSessionTargetOptions();if(mediaSessionTarget.innerHTML!==options){const old=mediaSessionTarget.value;mediaSessionTarget.innerHTML=options;if([...mediaSessionTarget.options].some(o=>o.value===old))mediaSessionTarget.value=old}"
new_refresh="if(!window.mediaSessionTarget)return;syncMediaSessionTargets()"
if old_refresh not in s: raise SystemExit('media target refresh source block not found')
s=s.replace(old_refresh,new_refresh,1)
p.write_text(s)
print('removed dynamic display-target HTML assignment from media session controls')
