#!/usr/bin/env python3
from pathlib import Path
p=Path(__file__).with_name('apply-automation-followup.py')
s=p.read_text()
s=s.replace("s=s.replace('automationTargetDomain(step.action)===automationTargetDomain(event.action)','automationTargetDomain(step.action)===automationTargetDomain(event.action)')","s=s.replace('stepDomain===\"display\"','[\"display-content\",\"display-overlay\"].includes(stepDomain)')\ns=s.replace('domain===\"display\"','[\"display-content\",\"display-overlay\"].includes(domain)')\ns=s.replace('domain!==\"display\"','![\"display-content\",\"display-overlay\"].includes(domain)')")
old="""old='''    if(delayMs>0)await wait(delayMs);\n\n    const stepEvent={...event,action:stepAction,targets:resolvedTargets,payload:step.payload||{}};'''\nnew='''    if(delayMs>0)await wait(delayMs);\n    if(event._occurrenceId&&automationCancelledOccurrences.has(event._occurrenceId))throw Object.assign(new Error(\"Automation run cancelled by operator\"),{code:\"AUTOMATION_CANCELLED\"});\n    if(!manual&&event.id){const current=classroomAutomations.events.find(item=>item.id===event.id);if(!current||current.enabled===false||Number(current.revision||1)!==Number(event.revision||1))throw Object.assign(new Error(\"Automation changed or was disabled while this run was waiting\"),{code:\"AUTOMATION_CONFIGURATION_CHANGED\"})}\n\n    const stepEvent={...event,action:stepAction,targets:resolvedTargets,payload:step.payload||{}};'''\ns=replace_once(s,old,new,'delayed step revalidation')"""
new="""old='''    const delay=Math.max(0,Number(step.delaySeconds||0));\n    if(delay)await new Promise(r=>setTimeout(r,delay*1000));\n    const stepAction=step.action||event.action;'''\nnew='''    const delay=Math.max(0,Number(step.delaySeconds||0));\n    if(delay)await new Promise(r=>setTimeout(r,delay*1000));\n    if(event._occurrenceId&&automationCancelledOccurrences.has(event._occurrenceId))throw Object.assign(new Error(\"Automation run cancelled by operator\"),{code:\"AUTOMATION_CANCELLED\"});\n    if(!manual&&event.id){const current=classroomAutomations.events.find(item=>item.id===event.id);if(!current||current.enabled===false||Number(current.revision||1)!==Number(event.revision||1))throw Object.assign(new Error(\"Automation changed or was disabled while this run was waiting\"),{code:\"AUTOMATION_CONFIGURATION_CHANGED\"})}\n    const stepAction=step.action||event.action;'''\ns=replace_once(s,old,new,'delayed step revalidation')"""
if old not in s: raise SystemExit('follow-up helper delay block not found')
s=s.replace(old,new,1)
p.write_text(s)
print('follow-up helper prepared')
